apiVersion: v1
kind: List
items:
- apiVersion: istio.io/v1alpha1
  kind: IstioConfig
  metadata:
    name: route-rule-details-default
    namespace: default
  spec:
    destination: details.default.svc.cluster.local
    precedence: 1
    route:
    - tags:
        version: v1
- apiVersion: istio.io/v1alpha1
  kind: IstioConfig
  metadata:
    name: route-rule-productpage-default
    namespace: default
  spec:
    destination: productpage.default.svc.cluster.local
    precedence: 1
    route:
    - tags:
        version: v1
- apiVersion: istio.io/v1alpha1
  kind: IstioConfig
  metadata:
    name: route-rule-ratings-default
    namespace: default
  spec:
    destination: ratings.default.svc.cluster.local
    precedence: 1
    route:
    - tags:
        version: v1
- apiVersion: istio.io/v1alpha1
  kind: IstioConfig
  metadata:
    name: route-rule-reviews-default
    namespace: default
  spec:
    destination: reviews.default.svc.cluster.local
    precedence: 1
    route:
    - tags:
        version: v1
